class IP {
    constructor(ip, pref){
        this.ip = ip;
        this.pref = pref;
    }

    stringToArray(){
        let array = [];
        const afterSplit = this.ip.split('.');
        array = afterSplit;
        return array;
    }

    decToBin(arr){
        arr.forEach((element, i) => {
            const ipAddrInt = parseInt(element);
            binary[i] = ipAddrInt.toString(2);
        })
      return binary.join('.');
    }
    
}